# ***************** Extensive Sawtooth Exhaustive

# ./src/examples/test-global --path ../data/world/dpomdp/ --problem mabc.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning -1 --frequence_upper_bound_pruning -1 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.1 --ostate_precision 0.1 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/
# ./src/examples/test-global --path ../data/world/dpomdp/ --problem mabc.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning -1 --frequence_upper_bound_pruning -1 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/

# ./src/examples/test-global --path ../data/world/dpomdp/ --problem recycling.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning -1 --frequence_upper_bound_pruning -1 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/
# ./src/examples/test-global --path ../data/world/dpomdp/ --problem recycling.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning 5 --frequence_upper_bound_pruning 5 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/

# ./src/examples/test-global --path ../data/world/dpomdp/ --problem GridSmall.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning 5 --frequence_upper_bound_pruning 5 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/
# ./src/examples/test-global --path ../data/world/dpomdp/ --problem GridSmall.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning -1 --frequence_upper_bound_pruning -1 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/
# ./src/examples/test-global --path ../data/world/dpomdp/ --problem GridSmall.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning -1 --frequence_upper_bound_pruning -1 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.1 --ostate_precision 0.1 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/

# ./src/examples/test-global --path ../data/world/dpomdp/ --problem GridSmall.dpomdp -f extensive-decpomdp -h 10 -m 2 -d 1 -e 0.01 --time 5000 --lower_bound maxplan_serial --upper_bound sawtooth --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning -1 --frequence_upper_bound_pruning -1 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/
# ./src/examples/test-global --path ../data/world/dpomdp/ --problem alignment_2x4.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 5000 --lower_bound maxplan_serial --upper_bound sawtooth --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning 5 --frequence_upper_bound_pruning 5 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/
# ./src/examples/test-global --path ../data/world/dpomdp/ --problem Mars.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 5000 --lower_bound maxplan_serial --upper_bound sawtooth --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning -1 --frequence_upper_bound_pruning -1 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.5 --ostate_precision 0.5 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/

./src/examples/test-global --path ../data/world/ndpomdp/ --problem example4_3-1.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning 5 --frequence_upper_bound_pruning 5 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/
./src/examples/test-global --path ../data/world/ndpomdp/ --problem example5P_3-1.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning 5 --frequence_upper_bound_pruning 5 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/
./src/examples/test-global --path ../data/world/ndpomdp/ --problem example7H_3-1.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning 5 --frequence_upper_bound_pruning 5 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/

# ***************** Extensive Sawtooth LP

# ./src/examples/test-global --path ../data/world/dpomdp/ --problem mabc.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth_lp_serial --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning -1 --frequence_upper_bound_pruning -1 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.1 --ostate_precision 0.1 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/
# ./src/examples/test-global --path ../data/world/dpomdp/ --problem mabc.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth_lp_serial --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning -1 --frequence_upper_bound_pruning -1 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/

# ./src/examples/test-global --path ../data/world/dpomdp/ --problem recycling.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth_lp_serial --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning -1 --frequence_upper_bound_pruning -1 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/
# ./src/examples/test-global --path ../data/world/dpomdp/ --problem recycling.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth_lp_serial --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning 5 --frequence_upper_bound_pruning 5 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/

# ./src/examples/test-global --path ../data/world/dpomdp/ --problem GridSmall.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth_lp_serial --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning 5 --frequence_upper_bound_pruning 5 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/
# ./src/examples/test-global --path ../data/world/dpomdp/ --problem GridSmall.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth_lp_serial --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning -1 --frequence_upper_bound_pruning -1 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/
# ./src/examples/test-global --path ../data/world/dpomdp/ --problem GridSmall.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth_lp_serial --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning -1 --frequence_upper_bound_pruning -1 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.1 --ostate_precision 0.1 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/

# ./src/examples/test-global --path ../data/world/dpomdp/ --problem alignment_2x4.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth_lp_serial --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning 5 --frequence_upper_bound_pruning 5 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/

# ./src/examples/test-global --path ../data/world/ndpomdp/ --problem example4_3-1.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth_lp_serial --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning 5 --frequence_upper_bound_pruning 5 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/
# ./src/examples/test-global --path ../data/world/ndpomdp/ --problem example5P_3-1.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth_lp_serial --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning 5 --frequence_upper_bound_pruning 5 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/
# ./src/examples/test-global --path ../data/world/ndpomdp/ --problem example7H_3-1.dpomdp -f extensive-decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_serial --upper_bound sawtooth_lp_serial --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning 5 --frequence_upper_bound_pruning 5 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/



# ***************** SImultatané

# ./src/examples/test-global --path ../data/world/dpomdp/ --problem mabc.dpomdp -f decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_lp --upper_bound sawtooth --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning -1 --frequence_upper_bound_pruning -1 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.001 --ostate_precision 0.001 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/

# ./src/examples/test-global --path ../data/world/dpomdp/ --problem recycling.dpomdp -f decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_lp --upper_bound sawtooth --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning -1 --frequence_upper_bound_pruning -1 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/
# ./src/examples/test-global --path ../data/world/dpomdp/ --problem recycling.dpomdp -f decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_lp --upper_bound sawtooth --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning 5 --frequence_upper_bound_pruning 5 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/

# ./src/examples/test-global --path ../data/world/dpomdp/ --problem GridSmall.dpomdp -f decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_lp --upper_bound sawtooth_lp --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning 5 --frequence_upper_bound_pruning 5 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/
# ./src/examples/test-global --path ../data/world/dpomdp/ --problem GridSmall.dpomdp -f decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_lp --upper_bound sawtooth_lp --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning -1 --frequence_upper_bound_pruning -1 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/
# ./src/examples/test-global --path ../data/world/dpomdp/ --problem GridSmall.dpomdp -f decpomdp -h 10 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_lp --upper_bound sawtooth_lp --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning -1 --frequence_upper_bound_pruning -1 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.1 --ostate_precision 0.1 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/

# ./src/examples/test-global --path ../data/world/dpomdp/ --problem alignment_2x4.dpomdp -f decpomdp -h 5 -m 1 -d 1 -e 0.01 --time 1000 --lower_bound maxplan_lp --upper_bound sawtooth_lp --lb_init Min --ub_init PomdpHsvi --frequence_lower_bound_pruning 5 --frequence_upper_bound_pruning 5 --type_of_lower_bound_pruning Bounded --type_of_upper_bound_pruning Global --belief_precision 0.01 --ostate_precision 0.01 --compress_precision 0.1 --save_path ../tests/tests_results/Test_jerome/

