.\" Manpage for sdms-test.
.\" Contact david.albert@insa-lyon.fr to correct errors or typos.
.TH sdms-test 1 "16 Mars 2021" "1.0" "sdms-test Manual"
.SH NAME
sdms-test \- test a saved policy in an environment.
.SH SYNOPSIS
sdms-test [--help] [<args>]
.SH DESCRIPTION
sdms-test program test a stored policy on a problem. This program only focus on testing and cannot optimize a policy.
.SH OPTIONS
The SDMStudio does not take any options. However, you can supply username.
.SH SEE ALSO
SDMStudio(1), sdms-solve(1), sdms-learn(1) 
.SH BUGS
No known bugs.
.SH AUTHOR
David Albert (david.albert@insa-lyon.fr)