.\" Manpage for sdms-learn.
.\" Contact david.albert@insa-lyon.fr to correct errors or typos.
.TH sdms-learn 1 "16 Mars 2021" "1.0" "sdms-learn Manual"
.SH NAME
sdms-learn \- solve a sequential decision making problem by reinforcement learning algorithm.
.SH SYNOPSIS
sdms-learn [--help] [<args>]
.SH DESCRIPTION
sdms-learn program aims at finding a solution of a decision making problem. This program only focus on reinforcement learning algorithms and does not take care of planning (See sdms-solve(1) to this end).
.SH OPTIONS
The SDMStudio does not take any options. However, you can supply username.
.SH SEE ALSO
SDMStudio(1), sdms-solve(1), sdms-test(1) 
.SH BUGS
No known bugs.
.SH AUTHOR
David Albert (david.albert@insa-lyon.fr)