.\" Manpage for SDM'Studio.
.\" Contact david.albert@insa-lyon.fr to correct errors or typos.
.TH sdms 1 "16 Mars 2021" "1.0" "sdms Manual"
.SH NAME
sdms \- the sequential decision making problem solver.
.SH SYNOPSIS
sdms [--version] [--help] <command> [<args>]
.SH DESCRIPTION
sdms is an efficient solver for games. The solver can be used to solve any kind of sequential decision making problems. Two class of algorithms are available (planning or reinforcement learning).
The first version of SDM'Studio can solve problems like : MDP, POMDP, Dec-POMDP, ZS-POSG, and event more. 

The main two algorithms implemented in the platform are HSVI (for planning field) and Q-learning (for reinforcement learning field). Further informations about the platform can be found on https://gitlab.inria.fr/chroma1/plasma/sdms.
.SH OPTIONS
.TP
.BR \-\-version
Show the version of the software.
.TP
.BR \-\-help
Produce help message.
.SH COMMANDS
.TP
.BR algorithms
Show available algorithms.
.TP
.TP
.BR formalisms
Show available formalisms.
.BR solve
Solve a decision making problem using planning algorithms.
.TP
.BR test
Test program. This program will test a given policy.
.TP
.BR worlds
Show available worlds.
.SH SEE ALSO
sdms-solve(1), sdms-learn(1), sdms-test(1) 
.SH BUGS
No known bugs.
.SH AUTHOR
David Albert (david.albert@insa-lyon.fr)